// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sr_cast (
        ap_ready,
        v_V,
        ap_return
);


output   ap_ready;
input  [29:0] v_V;
output  [7:0] ap_return;

wire   [0:0] tmp_fu_66_p3;
wire   [7:0] tmp_5_i_cast_fu_74_p1;
wire   [7:0] p_Val2_s_fu_48_p4;
wire   [7:0] p_Val2_1_fu_78_p2;
wire   [0:0] tmp_2_fu_84_p3;
wire   [0:0] p_Result_1_fu_58_p3;
wire   [0:0] rev_fu_92_p2;
wire   [1:0] tmp_1_fu_104_p4;
wire   [0:0] carry_1_fu_98_p2;
wire   [0:0] Range1_all_ones_fu_114_p2;
wire   [0:0] Range1_all_zeros_fu_120_p2;
wire   [0:0] phitmp_demorgan_i_fu_134_p2;
wire   [0:0] p_Result_s_fu_40_p3;
wire   [0:0] phitmp_i_fu_140_p2;
wire   [0:0] deleted_zeros_fu_126_p3;
wire   [0:0] p_110_demorgan_i_fu_152_p2;
wire   [0:0] p_Result_not_fu_164_p2;
wire   [0:0] p_not_i_fu_170_p2;
wire   [0:0] overflow_fu_158_p2;
wire   [0:0] brmerge_not_i_fu_176_p2;
wire   [0:0] neg_src_fu_146_p2;
wire   [0:0] brmerge_i_fu_182_p2;
wire   [7:0] p_mux_i_fu_188_p3;
wire   [7:0] p_i_fu_196_p3;

assign Range1_all_ones_fu_114_p2 = ((tmp_1_fu_104_p4 == 2'd3) ? 1'b1 : 1'b0);

assign Range1_all_zeros_fu_120_p2 = ((tmp_1_fu_104_p4 == 2'd0) ? 1'b1 : 1'b0);

assign ap_ready = 1'b1;

assign ap_return = ((brmerge_i_fu_182_p2[0:0] === 1'b1) ? p_mux_i_fu_188_p3 : p_i_fu_196_p3);

assign brmerge_i_fu_182_p2 = (p_not_i_fu_170_p2 | overflow_fu_158_p2);

assign brmerge_not_i_fu_176_p2 = (p_not_i_fu_170_p2 & p_110_demorgan_i_fu_152_p2);

assign carry_1_fu_98_p2 = (rev_fu_92_p2 & p_Result_1_fu_58_p3);

assign deleted_zeros_fu_126_p3 = ((carry_1_fu_98_p2[0:0] === 1'b1) ? Range1_all_ones_fu_114_p2 : Range1_all_zeros_fu_120_p2);

assign neg_src_fu_146_p2 = (phitmp_i_fu_140_p2 & p_Result_s_fu_40_p3);

assign overflow_fu_158_p2 = (p_110_demorgan_i_fu_152_p2 ^ 1'd1);

assign p_110_demorgan_i_fu_152_p2 = (p_Result_s_fu_40_p3 | deleted_zeros_fu_126_p3);

assign p_Result_1_fu_58_p3 = v_V[32'd27];

assign p_Result_not_fu_164_p2 = (p_Result_s_fu_40_p3 ^ 1'd1);

assign p_Result_s_fu_40_p3 = v_V[32'd29];

assign p_Val2_1_fu_78_p2 = (tmp_5_i_cast_fu_74_p1 + p_Val2_s_fu_48_p4);

assign p_Val2_s_fu_48_p4 = {{v_V[27:20]}};

assign p_i_fu_196_p3 = ((neg_src_fu_146_p2[0:0] === 1'b1) ? 8'd0 : p_Val2_1_fu_78_p2);

assign p_mux_i_fu_188_p3 = ((brmerge_not_i_fu_176_p2[0:0] === 1'b1) ? p_Val2_1_fu_78_p2 : 8'd255);

assign p_not_i_fu_170_p2 = (phitmp_demorgan_i_fu_134_p2 | p_Result_not_fu_164_p2);

assign phitmp_demorgan_i_fu_134_p2 = (carry_1_fu_98_p2 & Range1_all_ones_fu_114_p2);

assign phitmp_i_fu_140_p2 = (phitmp_demorgan_i_fu_134_p2 ^ 1'd1);

assign rev_fu_92_p2 = (tmp_2_fu_84_p3 ^ 1'd1);

assign tmp_1_fu_104_p4 = {{v_V[29:28]}};

assign tmp_2_fu_84_p3 = p_Val2_1_fu_78_p2[32'd7];

assign tmp_5_i_cast_fu_74_p1 = tmp_fu_66_p3;

assign tmp_fu_66_p3 = v_V[32'd19];

endmodule //sr_cast
