set_property IOSTANDARD TMDS_33 [get_ports TMDS_clk_n]
set_property PACKAGE_PIN N18 [get_ports TMDS_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports TMDS_clk_p]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[0]}]
set_property PACKAGE_PIN V20 [get_ports {TMDS_data_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[1]}]
set_property PACKAGE_PIN T20 [get_ports {TMDS_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_n[2]}]
set_property PACKAGE_PIN N20 [get_ports {TMDS_data_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {TMDS_data_p[2]}]
#set_property PACKAGE_PIN Y19 [get_ports {hdmi_hpd_tri_i[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_hpd_tri_i[0]}]
set_property PACKAGE_PIN V16 [get_ports hdmi_oen]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_oen]
set_property PACKAGE_PIN R18 [get_ports hdmi_ddc_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_ddc_scl_io]
set_property PACKAGE_PIN R16 [get_ports hdmi_ddc_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_ddc_sda_io]

set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[57]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arlen[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[47]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awlen[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[63]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rresp[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arlen[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[33]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awlen[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/mm2s_frame_ptr_out[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arburst[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arcache[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awburst[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awprot[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[55]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[49]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[54]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wstrb[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tkeep[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[52]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wstrb[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[57]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[43]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[62]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[51]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s2mm_frame_ptr_out[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arlen[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[58]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[36]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awlen[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awsize[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arprot[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awlen[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wstrb[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tuser[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s2mm_frame_ptr_out[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[34]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arlen[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_bresp[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[62]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[63]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/mm2s_frame_ptr_out[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arsize[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[53]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awcache[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wstrb[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[40]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arlen[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[61]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awlen[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[50]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[51]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awlen[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[41]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[52]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[45]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arburst[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wstrb[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awlen[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arprot[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/mm2s_frame_ptr_out[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s2mm_frame_ptr_out[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arsize[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[54]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[48]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[59]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arcache[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[46]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[59]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_bresp[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[39]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[47]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arlen[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[32]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awlen[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/mm2s_frame_ptr_out[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[33]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awburst[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arlen[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awprot[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[61]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wstrb[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wstrb[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s2mm_frame_ptr_out[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[44]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[35]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awsize[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[56]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[60]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[39]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[48]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[50]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wstrb[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[37]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arprot[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arcache[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[49]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[42]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[55]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[60]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[32]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arcache[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[40]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[46]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arsize[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[44]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[56]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[53]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s2mm_frame_ptr_out[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[36]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awsize[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[37]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awcache[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awprot[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[43]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[42]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[38]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_arlen[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[38]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/mm2s_frame_ptr_out[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rresp[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awcache[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awcache[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[34]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[35]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tkeep[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s2mm_frame_ptr_out[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[41]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[45]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[58]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/m_axis_mm2s_tkeep[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/mm2s_frame_ptr_out[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tkeep[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tkeep[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tkeep[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/axi_vdma_1/s_axis_s2mm_tuser[0]}]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/m_axi_s2mm_awready]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/m_axi_s2mm_bready]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/m_axi_s2mm_wlast]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/mm2s_introut]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/m_axi_mm2s_arready]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/m_axi_mm2s_rlast]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/m_axi_mm2s_rvalid]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/m_axis_mm2s_aclk]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/m_axis_mm2s_tlast]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/m_axis_mm2s_tready]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/s2mm_introut]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/m_axi_s2mm_aclk]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/m_axi_s2mm_awvalid]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/m_axi_s2mm_bvalid]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/m_axi_mm2s_arvalid]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/m_axi_mm2s_rready]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/m_axi_s2mm_wready]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/m_axi_s2mm_wvalid]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/m_axis_mm2s_tvalid]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/s_axis_s2mm_tlast]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/s_axis_s2mm_tready]
set_property MARK_DEBUG true [get_nets design_1_i/axi_vdma_1/s_axis_s2mm_tvalid]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 2 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_1_i/axi_vdma_1/m_axi_s2mm_bresp[0]} {design_1_i/axi_vdma_1/m_axi_s2mm_bresp[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 64 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[0]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[1]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[2]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[3]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[4]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[5]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[6]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[7]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[8]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[9]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[10]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[11]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[12]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[13]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[14]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[15]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[16]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[17]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[18]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[19]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[20]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[21]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[22]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[23]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[24]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[25]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[26]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[27]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[28]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[29]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[30]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[31]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[32]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[33]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[34]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[35]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[36]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[37]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[38]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[39]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[40]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[41]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[42]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[43]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[44]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[45]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[46]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[47]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[48]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[49]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[50]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[51]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[52]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[53]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[54]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[55]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[56]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[57]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[58]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[59]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[60]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[61]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[62]} {design_1_i/axi_vdma_1/m_axi_mm2s_rdata[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 3 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_1_i/axi_vdma_1/s_axis_s2mm_tkeep[0]} {design_1_i/axi_vdma_1/s_axis_s2mm_tkeep[1]} {design_1_i/axi_vdma_1/s_axis_s2mm_tkeep[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 4 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_1_i/axi_vdma_1/m_axi_mm2s_arcache[0]} {design_1_i/axi_vdma_1/m_axi_mm2s_arcache[1]} {design_1_i/axi_vdma_1/m_axi_mm2s_arcache[2]} {design_1_i/axi_vdma_1/m_axi_mm2s_arcache[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_1_i/axi_vdma_1/s_axis_s2mm_tuser[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 8 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_1_i/axi_vdma_1/m_axi_s2mm_wstrb[0]} {design_1_i/axi_vdma_1/m_axi_s2mm_wstrb[1]} {design_1_i/axi_vdma_1/m_axi_s2mm_wstrb[2]} {design_1_i/axi_vdma_1/m_axi_s2mm_wstrb[3]} {design_1_i/axi_vdma_1/m_axi_s2mm_wstrb[4]} {design_1_i/axi_vdma_1/m_axi_s2mm_wstrb[5]} {design_1_i/axi_vdma_1/m_axi_s2mm_wstrb[6]} {design_1_i/axi_vdma_1/m_axi_s2mm_wstrb[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 3 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_1_i/axi_vdma_1/m_axi_mm2s_arprot[0]} {design_1_i/axi_vdma_1/m_axi_mm2s_arprot[1]} {design_1_i/axi_vdma_1/m_axi_mm2s_arprot[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 6 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_1_i/axi_vdma_1/mm2s_frame_ptr_out[0]} {design_1_i/axi_vdma_1/mm2s_frame_ptr_out[1]} {design_1_i/axi_vdma_1/mm2s_frame_ptr_out[2]} {design_1_i/axi_vdma_1/mm2s_frame_ptr_out[3]} {design_1_i/axi_vdma_1/mm2s_frame_ptr_out[4]} {design_1_i/axi_vdma_1/mm2s_frame_ptr_out[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 64 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[0]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[1]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[2]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[3]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[4]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[5]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[6]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[7]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[8]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[9]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[10]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[11]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[12]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[13]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[14]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[15]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[16]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[17]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[18]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[19]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[20]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[21]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[22]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[23]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[24]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[25]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[26]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[27]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[28]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[29]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[30]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[31]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[32]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[33]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[34]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[35]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[36]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[37]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[38]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[39]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[40]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[41]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[42]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[43]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[44]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[45]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[46]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[47]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[48]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[49]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[50]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[51]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[52]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[53]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[54]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[55]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[56]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[57]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[58]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[59]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[60]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[61]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[62]} {design_1_i/axi_vdma_1/m_axi_s2mm_wdata[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 4 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_1_i/axi_vdma_1/m_axi_s2mm_awcache[0]} {design_1_i/axi_vdma_1/m_axi_s2mm_awcache[1]} {design_1_i/axi_vdma_1/m_axi_s2mm_awcache[2]} {design_1_i/axi_vdma_1/m_axi_s2mm_awcache[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 2 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {design_1_i/axi_vdma_1/m_axi_s2mm_awburst[0]} {design_1_i/axi_vdma_1/m_axi_s2mm_awburst[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 3 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {design_1_i/axi_vdma_1/m_axis_mm2s_tkeep[0]} {design_1_i/axi_vdma_1/m_axis_mm2s_tkeep[1]} {design_1_i/axi_vdma_1/m_axis_mm2s_tkeep[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 3 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {design_1_i/axi_vdma_1/m_axi_s2mm_awprot[0]} {design_1_i/axi_vdma_1/m_axi_s2mm_awprot[1]} {design_1_i/axi_vdma_1/m_axi_s2mm_awprot[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 2 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {design_1_i/axi_vdma_1/m_axi_mm2s_rresp[0]} {design_1_i/axi_vdma_1/m_axi_mm2s_rresp[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 24 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[0]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[1]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[2]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[3]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[4]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[5]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[6]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[7]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[8]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[9]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[10]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[11]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[12]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[13]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[14]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[15]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[16]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[17]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[18]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[19]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[20]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[21]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[22]} {design_1_i/axi_vdma_1/s_axis_s2mm_tdata[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 32 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[0]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[1]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[2]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[3]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[4]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[5]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[6]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[7]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[8]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[9]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[10]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[11]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[12]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[13]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[14]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[15]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[16]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[17]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[18]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[19]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[20]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[21]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[22]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[23]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[24]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[25]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[26]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[27]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[28]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[29]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[30]} {design_1_i/axi_vdma_1/m_axi_s2mm_awaddr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 8 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {design_1_i/axi_vdma_1/m_axi_mm2s_arlen[0]} {design_1_i/axi_vdma_1/m_axi_mm2s_arlen[1]} {design_1_i/axi_vdma_1/m_axi_mm2s_arlen[2]} {design_1_i/axi_vdma_1/m_axi_mm2s_arlen[3]} {design_1_i/axi_vdma_1/m_axi_mm2s_arlen[4]} {design_1_i/axi_vdma_1/m_axi_mm2s_arlen[5]} {design_1_i/axi_vdma_1/m_axi_mm2s_arlen[6]} {design_1_i/axi_vdma_1/m_axi_mm2s_arlen[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {design_1_i/axi_vdma_1/m_axis_mm2s_tuser[0]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 24 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[0]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[1]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[2]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[3]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[4]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[5]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[6]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[7]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[8]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[9]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[10]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[11]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[12]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[13]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[14]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[15]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[16]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[17]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[18]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[19]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[20]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[21]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[22]} {design_1_i/axi_vdma_1/m_axis_mm2s_tdata[23]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 3 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {design_1_i/axi_vdma_1/m_axi_mm2s_arsize[0]} {design_1_i/axi_vdma_1/m_axi_mm2s_arsize[1]} {design_1_i/axi_vdma_1/m_axi_mm2s_arsize[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 3 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {design_1_i/axi_vdma_1/m_axi_s2mm_awsize[0]} {design_1_i/axi_vdma_1/m_axi_s2mm_awsize[1]} {design_1_i/axi_vdma_1/m_axi_s2mm_awsize[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 8 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {design_1_i/axi_vdma_1/m_axi_s2mm_awlen[0]} {design_1_i/axi_vdma_1/m_axi_s2mm_awlen[1]} {design_1_i/axi_vdma_1/m_axi_s2mm_awlen[2]} {design_1_i/axi_vdma_1/m_axi_s2mm_awlen[3]} {design_1_i/axi_vdma_1/m_axi_s2mm_awlen[4]} {design_1_i/axi_vdma_1/m_axi_s2mm_awlen[5]} {design_1_i/axi_vdma_1/m_axi_s2mm_awlen[6]} {design_1_i/axi_vdma_1/m_axi_s2mm_awlen[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 32 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[0]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[1]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[2]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[3]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[4]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[5]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[6]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[7]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[8]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[9]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[10]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[11]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[12]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[13]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[14]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[15]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[16]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[17]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[18]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[19]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[20]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[21]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[22]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[23]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[24]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[25]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[26]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[27]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[28]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[29]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[30]} {design_1_i/axi_vdma_1/m_axi_mm2s_araddr[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 6 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list {design_1_i/axi_vdma_1/s2mm_frame_ptr_out[0]} {design_1_i/axi_vdma_1/s2mm_frame_ptr_out[1]} {design_1_i/axi_vdma_1/s2mm_frame_ptr_out[2]} {design_1_i/axi_vdma_1/s2mm_frame_ptr_out[3]} {design_1_i/axi_vdma_1/s2mm_frame_ptr_out[4]} {design_1_i/axi_vdma_1/s2mm_frame_ptr_out[5]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 2 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list {design_1_i/axi_vdma_1/m_axi_mm2s_arburst[0]} {design_1_i/axi_vdma_1/m_axi_mm2s_arburst[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list design_1_i/axi_vdma_1/m_axi_mm2s_arready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list design_1_i/axi_vdma_1/m_axi_mm2s_arvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list design_1_i/axi_vdma_1/m_axi_mm2s_rlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list design_1_i/axi_vdma_1/m_axi_mm2s_rready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list design_1_i/axi_vdma_1/m_axi_mm2s_rvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list design_1_i/axi_vdma_1/m_axi_s2mm_aclk]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list design_1_i/axi_vdma_1/m_axi_s2mm_awready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list design_1_i/axi_vdma_1/m_axi_s2mm_awvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list design_1_i/axi_vdma_1/m_axi_s2mm_bready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list design_1_i/axi_vdma_1/m_axi_s2mm_bvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list design_1_i/axi_vdma_1/m_axi_s2mm_wlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list design_1_i/axi_vdma_1/m_axi_s2mm_wready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list design_1_i/axi_vdma_1/m_axi_s2mm_wvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list design_1_i/axi_vdma_1/m_axis_mm2s_aclk]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list design_1_i/axi_vdma_1/m_axis_mm2s_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list design_1_i/axi_vdma_1/m_axis_mm2s_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list design_1_i/axi_vdma_1/m_axis_mm2s_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe42]
set_property port_width 1 [get_debug_ports u_ila_0/probe42]
connect_debug_port u_ila_0/probe42 [get_nets [list design_1_i/axi_vdma_1/mm2s_introut]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe43]
set_property port_width 1 [get_debug_ports u_ila_0/probe43]
connect_debug_port u_ila_0/probe43 [get_nets [list design_1_i/axi_vdma_1/s2mm_introut]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe44]
set_property port_width 1 [get_debug_ports u_ila_0/probe44]
connect_debug_port u_ila_0/probe44 [get_nets [list design_1_i/axi_vdma_1/s_axis_s2mm_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe45]
set_property port_width 1 [get_debug_ports u_ila_0/probe45]
connect_debug_port u_ila_0/probe45 [get_nets [list design_1_i/axi_vdma_1/s_axis_s2mm_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe46]
set_property port_width 1 [get_debug_ports u_ila_0/probe46]
connect_debug_port u_ila_0/probe46 [get_nets [list design_1_i/axi_vdma_1/s_axis_s2mm_tvalid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
