-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity my_hls_resize is
port (
    src_axi_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
    src_axi_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
    src_axi_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
    src_axi_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    src_axi_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    src_axi_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    src_axi_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    dst_axi_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    dst_axi_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    dst_axi_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    dst_axi_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_axi_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_axi_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    dst_axi_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    src_axi_TVALID : IN STD_LOGIC;
    src_axi_TREADY : OUT STD_LOGIC;
    dst_axi_TVALID : OUT STD_LOGIC;
    dst_axi_TREADY : IN STD_LOGIC );
end;


architecture behav of my_hls_resize is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "my_hls_resize,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=11.010000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=24,HLS_SYN_DSP=26,HLS_SYN_FF=9129,HLS_SYN_LUT=7140,HLS_VERSION=2018_3}";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal Block_proc_U0_ap_start : STD_LOGIC;
    signal Block_proc_U0_ap_done : STD_LOGIC;
    signal Block_proc_U0_ap_continue : STD_LOGIC;
    signal Block_proc_U0_ap_idle : STD_LOGIC;
    signal Block_proc_U0_ap_ready : STD_LOGIC;
    signal Block_proc_U0_start_out : STD_LOGIC;
    signal Block_proc_U0_start_write : STD_LOGIC;
    signal Block_proc_U0_imag_0_rows_V_out_din : STD_LOGIC_VECTOR (10 downto 0);
    signal Block_proc_U0_imag_0_rows_V_out_write : STD_LOGIC;
    signal Block_proc_U0_imag_0_cols_V_out_din : STD_LOGIC_VECTOR (10 downto 0);
    signal Block_proc_U0_imag_0_cols_V_out_write : STD_LOGIC;
    signal Block_proc_U0_imag_1_rows_V_out_din : STD_LOGIC_VECTOR (12 downto 0);
    signal Block_proc_U0_imag_1_rows_V_out_write : STD_LOGIC;
    signal Block_proc_U0_imag_1_cols_V_out_din : STD_LOGIC_VECTOR (12 downto 0);
    signal Block_proc_U0_imag_1_cols_V_out_write : STD_LOGIC;
    signal AXIvideo2Mat_U0_ap_start : STD_LOGIC;
    signal AXIvideo2Mat_U0_ap_done : STD_LOGIC;
    signal AXIvideo2Mat_U0_ap_continue : STD_LOGIC;
    signal AXIvideo2Mat_U0_ap_idle : STD_LOGIC;
    signal AXIvideo2Mat_U0_ap_ready : STD_LOGIC;
    signal AXIvideo2Mat_U0_src_axi_TREADY : STD_LOGIC;
    signal AXIvideo2Mat_U0_img_rows_V_read : STD_LOGIC;
    signal AXIvideo2Mat_U0_img_cols_V_read : STD_LOGIC;
    signal AXIvideo2Mat_U0_img_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal AXIvideo2Mat_U0_img_data_stream_0_V_write : STD_LOGIC;
    signal AXIvideo2Mat_U0_img_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal AXIvideo2Mat_U0_img_data_stream_1_V_write : STD_LOGIC;
    signal AXIvideo2Mat_U0_img_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal AXIvideo2Mat_U0_img_data_stream_2_V_write : STD_LOGIC;
    signal AXIvideo2Mat_U0_img_rows_V_out_din : STD_LOGIC_VECTOR (10 downto 0);
    signal AXIvideo2Mat_U0_img_rows_V_out_write : STD_LOGIC;
    signal AXIvideo2Mat_U0_img_cols_V_out_din : STD_LOGIC_VECTOR (10 downto 0);
    signal AXIvideo2Mat_U0_img_cols_V_out_write : STD_LOGIC;
    signal Resize_U0_ap_start : STD_LOGIC;
    signal Resize_U0_ap_done : STD_LOGIC;
    signal Resize_U0_ap_continue : STD_LOGIC;
    signal Resize_U0_ap_idle : STD_LOGIC;
    signal Resize_U0_ap_ready : STD_LOGIC;
    signal Resize_U0_start_out : STD_LOGIC;
    signal Resize_U0_start_write : STD_LOGIC;
    signal Resize_U0_p_src_rows_V_read : STD_LOGIC;
    signal Resize_U0_p_src_cols_V_read : STD_LOGIC;
    signal Resize_U0_p_src_data_stream_0_V_read : STD_LOGIC;
    signal Resize_U0_p_src_data_stream_1_V_read : STD_LOGIC;
    signal Resize_U0_p_src_data_stream_2_V_read : STD_LOGIC;
    signal Resize_U0_p_dst_rows_V_read : STD_LOGIC;
    signal Resize_U0_p_dst_cols_V_read : STD_LOGIC;
    signal Resize_U0_p_dst_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Resize_U0_p_dst_data_stream_0_V_write : STD_LOGIC;
    signal Resize_U0_p_dst_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Resize_U0_p_dst_data_stream_1_V_write : STD_LOGIC;
    signal Resize_U0_p_dst_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Resize_U0_p_dst_data_stream_2_V_write : STD_LOGIC;
    signal Resize_U0_p_dst_rows_V_out_din : STD_LOGIC_VECTOR (12 downto 0);
    signal Resize_U0_p_dst_rows_V_out_write : STD_LOGIC;
    signal Resize_U0_p_dst_cols_V_out_din : STD_LOGIC_VECTOR (12 downto 0);
    signal Resize_U0_p_dst_cols_V_out_write : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_start : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_done : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_continue : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_idle : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_ready : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_rows_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_cols_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_data_stream_0_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_data_stream_1_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_data_stream_2_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_dst_axi_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal Mat2AXIvideo_U0_dst_axi_TVALID : STD_LOGIC;
    signal Mat2AXIvideo_U0_dst_axi_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal Mat2AXIvideo_U0_dst_axi_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal Mat2AXIvideo_U0_dst_axi_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Mat2AXIvideo_U0_dst_axi_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal Mat2AXIvideo_U0_dst_axi_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal Mat2AXIvideo_U0_dst_axi_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sync_continue : STD_LOGIC;
    signal imag_0_rows_V_c_full_n : STD_LOGIC;
    signal imag_0_rows_V_c_dout : STD_LOGIC_VECTOR (10 downto 0);
    signal imag_0_rows_V_c_empty_n : STD_LOGIC;
    signal imag_0_cols_V_c_full_n : STD_LOGIC;
    signal imag_0_cols_V_c_dout : STD_LOGIC_VECTOR (10 downto 0);
    signal imag_0_cols_V_c_empty_n : STD_LOGIC;
    signal imag_1_rows_V_c_full_n : STD_LOGIC;
    signal imag_1_rows_V_c_dout : STD_LOGIC_VECTOR (12 downto 0);
    signal imag_1_rows_V_c_empty_n : STD_LOGIC;
    signal imag_1_cols_V_c_full_n : STD_LOGIC;
    signal imag_1_cols_V_c_dout : STD_LOGIC_VECTOR (12 downto 0);
    signal imag_1_cols_V_c_empty_n : STD_LOGIC;
    signal imag_0_data_stream_0_full_n : STD_LOGIC;
    signal imag_0_data_stream_0_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal imag_0_data_stream_0_empty_n : STD_LOGIC;
    signal imag_0_data_stream_1_full_n : STD_LOGIC;
    signal imag_0_data_stream_1_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal imag_0_data_stream_1_empty_n : STD_LOGIC;
    signal imag_0_data_stream_2_full_n : STD_LOGIC;
    signal imag_0_data_stream_2_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal imag_0_data_stream_2_empty_n : STD_LOGIC;
    signal imag_0_rows_V_c8_full_n : STD_LOGIC;
    signal imag_0_rows_V_c8_dout : STD_LOGIC_VECTOR (10 downto 0);
    signal imag_0_rows_V_c8_empty_n : STD_LOGIC;
    signal imag_0_cols_V_c9_full_n : STD_LOGIC;
    signal imag_0_cols_V_c9_dout : STD_LOGIC_VECTOR (10 downto 0);
    signal imag_0_cols_V_c9_empty_n : STD_LOGIC;
    signal imag_1_data_stream_0_full_n : STD_LOGIC;
    signal imag_1_data_stream_0_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal imag_1_data_stream_0_empty_n : STD_LOGIC;
    signal imag_1_data_stream_1_full_n : STD_LOGIC;
    signal imag_1_data_stream_1_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal imag_1_data_stream_1_empty_n : STD_LOGIC;
    signal imag_1_data_stream_2_full_n : STD_LOGIC;
    signal imag_1_data_stream_2_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal imag_1_data_stream_2_empty_n : STD_LOGIC;
    signal imag_1_rows_V_c10_full_n : STD_LOGIC;
    signal imag_1_rows_V_c10_dout : STD_LOGIC_VECTOR (12 downto 0);
    signal imag_1_rows_V_c10_empty_n : STD_LOGIC;
    signal imag_1_cols_V_c11_full_n : STD_LOGIC;
    signal imag_1_cols_V_c11_dout : STD_LOGIC_VECTOR (12 downto 0);
    signal imag_1_cols_V_c11_empty_n : STD_LOGIC;
    signal start_for_Resize_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Resize_U0_full_n : STD_LOGIC;
    signal start_for_Resize_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Resize_U0_empty_n : STD_LOGIC;
    signal AXIvideo2Mat_U0_start_full_n : STD_LOGIC;
    signal AXIvideo2Mat_U0_start_write : STD_LOGIC;
    signal start_for_Mat2AXIvideo_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Mat2AXIvideo_U0_full_n : STD_LOGIC;
    signal start_for_Mat2AXIvideo_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Mat2AXIvideo_U0_empty_n : STD_LOGIC;
    signal Mat2AXIvideo_U0_start_full_n : STD_LOGIC;
    signal Mat2AXIvideo_U0_start_write : STD_LOGIC;

    component Block_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        imag_0_rows_V_out_din : OUT STD_LOGIC_VECTOR (10 downto 0);
        imag_0_rows_V_out_full_n : IN STD_LOGIC;
        imag_0_rows_V_out_write : OUT STD_LOGIC;
        imag_0_cols_V_out_din : OUT STD_LOGIC_VECTOR (10 downto 0);
        imag_0_cols_V_out_full_n : IN STD_LOGIC;
        imag_0_cols_V_out_write : OUT STD_LOGIC;
        imag_1_rows_V_out_din : OUT STD_LOGIC_VECTOR (12 downto 0);
        imag_1_rows_V_out_full_n : IN STD_LOGIC;
        imag_1_rows_V_out_write : OUT STD_LOGIC;
        imag_1_cols_V_out_din : OUT STD_LOGIC_VECTOR (12 downto 0);
        imag_1_cols_V_out_full_n : IN STD_LOGIC;
        imag_1_cols_V_out_write : OUT STD_LOGIC );
    end component;


    component AXIvideo2Mat IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        src_axi_TDATA : IN STD_LOGIC_VECTOR (23 downto 0);
        src_axi_TVALID : IN STD_LOGIC;
        src_axi_TREADY : OUT STD_LOGIC;
        src_axi_TKEEP : IN STD_LOGIC_VECTOR (2 downto 0);
        src_axi_TSTRB : IN STD_LOGIC_VECTOR (2 downto 0);
        src_axi_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        src_axi_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        src_axi_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        src_axi_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        img_rows_V_dout : IN STD_LOGIC_VECTOR (10 downto 0);
        img_rows_V_empty_n : IN STD_LOGIC;
        img_rows_V_read : OUT STD_LOGIC;
        img_cols_V_dout : IN STD_LOGIC_VECTOR (10 downto 0);
        img_cols_V_empty_n : IN STD_LOGIC;
        img_cols_V_read : OUT STD_LOGIC;
        img_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_0_V_full_n : IN STD_LOGIC;
        img_data_stream_0_V_write : OUT STD_LOGIC;
        img_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_1_V_full_n : IN STD_LOGIC;
        img_data_stream_1_V_write : OUT STD_LOGIC;
        img_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_2_V_full_n : IN STD_LOGIC;
        img_data_stream_2_V_write : OUT STD_LOGIC;
        img_rows_V_out_din : OUT STD_LOGIC_VECTOR (10 downto 0);
        img_rows_V_out_full_n : IN STD_LOGIC;
        img_rows_V_out_write : OUT STD_LOGIC;
        img_cols_V_out_din : OUT STD_LOGIC_VECTOR (10 downto 0);
        img_cols_V_out_full_n : IN STD_LOGIC;
        img_cols_V_out_write : OUT STD_LOGIC );
    end component;


    component Resize IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        p_src_rows_V_dout : IN STD_LOGIC_VECTOR (10 downto 0);
        p_src_rows_V_empty_n : IN STD_LOGIC;
        p_src_rows_V_read : OUT STD_LOGIC;
        p_src_cols_V_dout : IN STD_LOGIC_VECTOR (10 downto 0);
        p_src_cols_V_empty_n : IN STD_LOGIC;
        p_src_cols_V_read : OUT STD_LOGIC;
        p_src_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_src_data_stream_0_V_empty_n : IN STD_LOGIC;
        p_src_data_stream_0_V_read : OUT STD_LOGIC;
        p_src_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_src_data_stream_1_V_empty_n : IN STD_LOGIC;
        p_src_data_stream_1_V_read : OUT STD_LOGIC;
        p_src_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        p_src_data_stream_2_V_empty_n : IN STD_LOGIC;
        p_src_data_stream_2_V_read : OUT STD_LOGIC;
        p_dst_rows_V_dout : IN STD_LOGIC_VECTOR (12 downto 0);
        p_dst_rows_V_empty_n : IN STD_LOGIC;
        p_dst_rows_V_read : OUT STD_LOGIC;
        p_dst_cols_V_dout : IN STD_LOGIC_VECTOR (12 downto 0);
        p_dst_cols_V_empty_n : IN STD_LOGIC;
        p_dst_cols_V_read : OUT STD_LOGIC;
        p_dst_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_dst_data_stream_0_V_full_n : IN STD_LOGIC;
        p_dst_data_stream_0_V_write : OUT STD_LOGIC;
        p_dst_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_dst_data_stream_1_V_full_n : IN STD_LOGIC;
        p_dst_data_stream_1_V_write : OUT STD_LOGIC;
        p_dst_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        p_dst_data_stream_2_V_full_n : IN STD_LOGIC;
        p_dst_data_stream_2_V_write : OUT STD_LOGIC;
        p_dst_rows_V_out_din : OUT STD_LOGIC_VECTOR (12 downto 0);
        p_dst_rows_V_out_full_n : IN STD_LOGIC;
        p_dst_rows_V_out_write : OUT STD_LOGIC;
        p_dst_cols_V_out_din : OUT STD_LOGIC_VECTOR (12 downto 0);
        p_dst_cols_V_out_full_n : IN STD_LOGIC;
        p_dst_cols_V_out_write : OUT STD_LOGIC );
    end component;


    component Mat2AXIvideo IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_rows_V_dout : IN STD_LOGIC_VECTOR (12 downto 0);
        img_rows_V_empty_n : IN STD_LOGIC;
        img_rows_V_read : OUT STD_LOGIC;
        img_cols_V_dout : IN STD_LOGIC_VECTOR (12 downto 0);
        img_cols_V_empty_n : IN STD_LOGIC;
        img_cols_V_read : OUT STD_LOGIC;
        img_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_0_V_empty_n : IN STD_LOGIC;
        img_data_stream_0_V_read : OUT STD_LOGIC;
        img_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_1_V_empty_n : IN STD_LOGIC;
        img_data_stream_1_V_read : OUT STD_LOGIC;
        img_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_2_V_empty_n : IN STD_LOGIC;
        img_data_stream_2_V_read : OUT STD_LOGIC;
        dst_axi_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        dst_axi_TVALID : OUT STD_LOGIC;
        dst_axi_TREADY : IN STD_LOGIC;
        dst_axi_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        dst_axi_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        dst_axi_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        dst_axi_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        dst_axi_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        dst_axi_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component fifo_w11_d2_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (10 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (10 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fifo_w13_d3_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (12 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (12 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fifo_w8_d2_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component fifo_w13_d2_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (12 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (12 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_Resize_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_Mat2AXICeG IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    Block_proc_U0 : component Block_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_proc_U0_ap_start,
        start_full_n => start_for_Resize_U0_full_n,
        ap_done => Block_proc_U0_ap_done,
        ap_continue => Block_proc_U0_ap_continue,
        ap_idle => Block_proc_U0_ap_idle,
        ap_ready => Block_proc_U0_ap_ready,
        start_out => Block_proc_U0_start_out,
        start_write => Block_proc_U0_start_write,
        imag_0_rows_V_out_din => Block_proc_U0_imag_0_rows_V_out_din,
        imag_0_rows_V_out_full_n => imag_0_rows_V_c_full_n,
        imag_0_rows_V_out_write => Block_proc_U0_imag_0_rows_V_out_write,
        imag_0_cols_V_out_din => Block_proc_U0_imag_0_cols_V_out_din,
        imag_0_cols_V_out_full_n => imag_0_cols_V_c_full_n,
        imag_0_cols_V_out_write => Block_proc_U0_imag_0_cols_V_out_write,
        imag_1_rows_V_out_din => Block_proc_U0_imag_1_rows_V_out_din,
        imag_1_rows_V_out_full_n => imag_1_rows_V_c_full_n,
        imag_1_rows_V_out_write => Block_proc_U0_imag_1_rows_V_out_write,
        imag_1_cols_V_out_din => Block_proc_U0_imag_1_cols_V_out_din,
        imag_1_cols_V_out_full_n => imag_1_cols_V_c_full_n,
        imag_1_cols_V_out_write => Block_proc_U0_imag_1_cols_V_out_write);

    AXIvideo2Mat_U0 : component AXIvideo2Mat
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => AXIvideo2Mat_U0_ap_start,
        ap_done => AXIvideo2Mat_U0_ap_done,
        ap_continue => AXIvideo2Mat_U0_ap_continue,
        ap_idle => AXIvideo2Mat_U0_ap_idle,
        ap_ready => AXIvideo2Mat_U0_ap_ready,
        src_axi_TDATA => src_axi_TDATA,
        src_axi_TVALID => src_axi_TVALID,
        src_axi_TREADY => AXIvideo2Mat_U0_src_axi_TREADY,
        src_axi_TKEEP => src_axi_TKEEP,
        src_axi_TSTRB => src_axi_TSTRB,
        src_axi_TUSER => src_axi_TUSER,
        src_axi_TLAST => src_axi_TLAST,
        src_axi_TID => src_axi_TID,
        src_axi_TDEST => src_axi_TDEST,
        img_rows_V_dout => imag_0_rows_V_c_dout,
        img_rows_V_empty_n => imag_0_rows_V_c_empty_n,
        img_rows_V_read => AXIvideo2Mat_U0_img_rows_V_read,
        img_cols_V_dout => imag_0_cols_V_c_dout,
        img_cols_V_empty_n => imag_0_cols_V_c_empty_n,
        img_cols_V_read => AXIvideo2Mat_U0_img_cols_V_read,
        img_data_stream_0_V_din => AXIvideo2Mat_U0_img_data_stream_0_V_din,
        img_data_stream_0_V_full_n => imag_0_data_stream_0_full_n,
        img_data_stream_0_V_write => AXIvideo2Mat_U0_img_data_stream_0_V_write,
        img_data_stream_1_V_din => AXIvideo2Mat_U0_img_data_stream_1_V_din,
        img_data_stream_1_V_full_n => imag_0_data_stream_1_full_n,
        img_data_stream_1_V_write => AXIvideo2Mat_U0_img_data_stream_1_V_write,
        img_data_stream_2_V_din => AXIvideo2Mat_U0_img_data_stream_2_V_din,
        img_data_stream_2_V_full_n => imag_0_data_stream_2_full_n,
        img_data_stream_2_V_write => AXIvideo2Mat_U0_img_data_stream_2_V_write,
        img_rows_V_out_din => AXIvideo2Mat_U0_img_rows_V_out_din,
        img_rows_V_out_full_n => imag_0_rows_V_c8_full_n,
        img_rows_V_out_write => AXIvideo2Mat_U0_img_rows_V_out_write,
        img_cols_V_out_din => AXIvideo2Mat_U0_img_cols_V_out_din,
        img_cols_V_out_full_n => imag_0_cols_V_c9_full_n,
        img_cols_V_out_write => AXIvideo2Mat_U0_img_cols_V_out_write);

    Resize_U0 : component Resize
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Resize_U0_ap_start,
        start_full_n => start_for_Mat2AXIvideo_U0_full_n,
        ap_done => Resize_U0_ap_done,
        ap_continue => Resize_U0_ap_continue,
        ap_idle => Resize_U0_ap_idle,
        ap_ready => Resize_U0_ap_ready,
        start_out => Resize_U0_start_out,
        start_write => Resize_U0_start_write,
        p_src_rows_V_dout => imag_0_rows_V_c8_dout,
        p_src_rows_V_empty_n => imag_0_rows_V_c8_empty_n,
        p_src_rows_V_read => Resize_U0_p_src_rows_V_read,
        p_src_cols_V_dout => imag_0_cols_V_c9_dout,
        p_src_cols_V_empty_n => imag_0_cols_V_c9_empty_n,
        p_src_cols_V_read => Resize_U0_p_src_cols_V_read,
        p_src_data_stream_0_V_dout => imag_0_data_stream_0_dout,
        p_src_data_stream_0_V_empty_n => imag_0_data_stream_0_empty_n,
        p_src_data_stream_0_V_read => Resize_U0_p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout => imag_0_data_stream_1_dout,
        p_src_data_stream_1_V_empty_n => imag_0_data_stream_1_empty_n,
        p_src_data_stream_1_V_read => Resize_U0_p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout => imag_0_data_stream_2_dout,
        p_src_data_stream_2_V_empty_n => imag_0_data_stream_2_empty_n,
        p_src_data_stream_2_V_read => Resize_U0_p_src_data_stream_2_V_read,
        p_dst_rows_V_dout => imag_1_rows_V_c_dout,
        p_dst_rows_V_empty_n => imag_1_rows_V_c_empty_n,
        p_dst_rows_V_read => Resize_U0_p_dst_rows_V_read,
        p_dst_cols_V_dout => imag_1_cols_V_c_dout,
        p_dst_cols_V_empty_n => imag_1_cols_V_c_empty_n,
        p_dst_cols_V_read => Resize_U0_p_dst_cols_V_read,
        p_dst_data_stream_0_V_din => Resize_U0_p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n => imag_1_data_stream_0_full_n,
        p_dst_data_stream_0_V_write => Resize_U0_p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din => Resize_U0_p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n => imag_1_data_stream_1_full_n,
        p_dst_data_stream_1_V_write => Resize_U0_p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din => Resize_U0_p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n => imag_1_data_stream_2_full_n,
        p_dst_data_stream_2_V_write => Resize_U0_p_dst_data_stream_2_V_write,
        p_dst_rows_V_out_din => Resize_U0_p_dst_rows_V_out_din,
        p_dst_rows_V_out_full_n => imag_1_rows_V_c10_full_n,
        p_dst_rows_V_out_write => Resize_U0_p_dst_rows_V_out_write,
        p_dst_cols_V_out_din => Resize_U0_p_dst_cols_V_out_din,
        p_dst_cols_V_out_full_n => imag_1_cols_V_c11_full_n,
        p_dst_cols_V_out_write => Resize_U0_p_dst_cols_V_out_write);

    Mat2AXIvideo_U0 : component Mat2AXIvideo
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Mat2AXIvideo_U0_ap_start,
        ap_done => Mat2AXIvideo_U0_ap_done,
        ap_continue => Mat2AXIvideo_U0_ap_continue,
        ap_idle => Mat2AXIvideo_U0_ap_idle,
        ap_ready => Mat2AXIvideo_U0_ap_ready,
        img_rows_V_dout => imag_1_rows_V_c10_dout,
        img_rows_V_empty_n => imag_1_rows_V_c10_empty_n,
        img_rows_V_read => Mat2AXIvideo_U0_img_rows_V_read,
        img_cols_V_dout => imag_1_cols_V_c11_dout,
        img_cols_V_empty_n => imag_1_cols_V_c11_empty_n,
        img_cols_V_read => Mat2AXIvideo_U0_img_cols_V_read,
        img_data_stream_0_V_dout => imag_1_data_stream_0_dout,
        img_data_stream_0_V_empty_n => imag_1_data_stream_0_empty_n,
        img_data_stream_0_V_read => Mat2AXIvideo_U0_img_data_stream_0_V_read,
        img_data_stream_1_V_dout => imag_1_data_stream_1_dout,
        img_data_stream_1_V_empty_n => imag_1_data_stream_1_empty_n,
        img_data_stream_1_V_read => Mat2AXIvideo_U0_img_data_stream_1_V_read,
        img_data_stream_2_V_dout => imag_1_data_stream_2_dout,
        img_data_stream_2_V_empty_n => imag_1_data_stream_2_empty_n,
        img_data_stream_2_V_read => Mat2AXIvideo_U0_img_data_stream_2_V_read,
        dst_axi_TDATA => Mat2AXIvideo_U0_dst_axi_TDATA,
        dst_axi_TVALID => Mat2AXIvideo_U0_dst_axi_TVALID,
        dst_axi_TREADY => dst_axi_TREADY,
        dst_axi_TKEEP => Mat2AXIvideo_U0_dst_axi_TKEEP,
        dst_axi_TSTRB => Mat2AXIvideo_U0_dst_axi_TSTRB,
        dst_axi_TUSER => Mat2AXIvideo_U0_dst_axi_TUSER,
        dst_axi_TLAST => Mat2AXIvideo_U0_dst_axi_TLAST,
        dst_axi_TID => Mat2AXIvideo_U0_dst_axi_TID,
        dst_axi_TDEST => Mat2AXIvideo_U0_dst_axi_TDEST);

    imag_0_rows_V_c_U : component fifo_w11_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_proc_U0_imag_0_rows_V_out_din,
        if_full_n => imag_0_rows_V_c_full_n,
        if_write => Block_proc_U0_imag_0_rows_V_out_write,
        if_dout => imag_0_rows_V_c_dout,
        if_empty_n => imag_0_rows_V_c_empty_n,
        if_read => AXIvideo2Mat_U0_img_rows_V_read);

    imag_0_cols_V_c_U : component fifo_w11_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_proc_U0_imag_0_cols_V_out_din,
        if_full_n => imag_0_cols_V_c_full_n,
        if_write => Block_proc_U0_imag_0_cols_V_out_write,
        if_dout => imag_0_cols_V_c_dout,
        if_empty_n => imag_0_cols_V_c_empty_n,
        if_read => AXIvideo2Mat_U0_img_cols_V_read);

    imag_1_rows_V_c_U : component fifo_w13_d3_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_proc_U0_imag_1_rows_V_out_din,
        if_full_n => imag_1_rows_V_c_full_n,
        if_write => Block_proc_U0_imag_1_rows_V_out_write,
        if_dout => imag_1_rows_V_c_dout,
        if_empty_n => imag_1_rows_V_c_empty_n,
        if_read => Resize_U0_p_dst_rows_V_read);

    imag_1_cols_V_c_U : component fifo_w13_d3_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Block_proc_U0_imag_1_cols_V_out_din,
        if_full_n => imag_1_cols_V_c_full_n,
        if_write => Block_proc_U0_imag_1_cols_V_out_write,
        if_dout => imag_1_cols_V_c_dout,
        if_empty_n => imag_1_cols_V_c_empty_n,
        if_read => Resize_U0_p_dst_cols_V_read);

    imag_0_data_stream_0_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2Mat_U0_img_data_stream_0_V_din,
        if_full_n => imag_0_data_stream_0_full_n,
        if_write => AXIvideo2Mat_U0_img_data_stream_0_V_write,
        if_dout => imag_0_data_stream_0_dout,
        if_empty_n => imag_0_data_stream_0_empty_n,
        if_read => Resize_U0_p_src_data_stream_0_V_read);

    imag_0_data_stream_1_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2Mat_U0_img_data_stream_1_V_din,
        if_full_n => imag_0_data_stream_1_full_n,
        if_write => AXIvideo2Mat_U0_img_data_stream_1_V_write,
        if_dout => imag_0_data_stream_1_dout,
        if_empty_n => imag_0_data_stream_1_empty_n,
        if_read => Resize_U0_p_src_data_stream_1_V_read);

    imag_0_data_stream_2_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2Mat_U0_img_data_stream_2_V_din,
        if_full_n => imag_0_data_stream_2_full_n,
        if_write => AXIvideo2Mat_U0_img_data_stream_2_V_write,
        if_dout => imag_0_data_stream_2_dout,
        if_empty_n => imag_0_data_stream_2_empty_n,
        if_read => Resize_U0_p_src_data_stream_2_V_read);

    imag_0_rows_V_c8_U : component fifo_w11_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2Mat_U0_img_rows_V_out_din,
        if_full_n => imag_0_rows_V_c8_full_n,
        if_write => AXIvideo2Mat_U0_img_rows_V_out_write,
        if_dout => imag_0_rows_V_c8_dout,
        if_empty_n => imag_0_rows_V_c8_empty_n,
        if_read => Resize_U0_p_src_rows_V_read);

    imag_0_cols_V_c9_U : component fifo_w11_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2Mat_U0_img_cols_V_out_din,
        if_full_n => imag_0_cols_V_c9_full_n,
        if_write => AXIvideo2Mat_U0_img_cols_V_out_write,
        if_dout => imag_0_cols_V_c9_dout,
        if_empty_n => imag_0_cols_V_c9_empty_n,
        if_read => Resize_U0_p_src_cols_V_read);

    imag_1_data_stream_0_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Resize_U0_p_dst_data_stream_0_V_din,
        if_full_n => imag_1_data_stream_0_full_n,
        if_write => Resize_U0_p_dst_data_stream_0_V_write,
        if_dout => imag_1_data_stream_0_dout,
        if_empty_n => imag_1_data_stream_0_empty_n,
        if_read => Mat2AXIvideo_U0_img_data_stream_0_V_read);

    imag_1_data_stream_1_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Resize_U0_p_dst_data_stream_1_V_din,
        if_full_n => imag_1_data_stream_1_full_n,
        if_write => Resize_U0_p_dst_data_stream_1_V_write,
        if_dout => imag_1_data_stream_1_dout,
        if_empty_n => imag_1_data_stream_1_empty_n,
        if_read => Mat2AXIvideo_U0_img_data_stream_1_V_read);

    imag_1_data_stream_2_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Resize_U0_p_dst_data_stream_2_V_din,
        if_full_n => imag_1_data_stream_2_full_n,
        if_write => Resize_U0_p_dst_data_stream_2_V_write,
        if_dout => imag_1_data_stream_2_dout,
        if_empty_n => imag_1_data_stream_2_empty_n,
        if_read => Mat2AXIvideo_U0_img_data_stream_2_V_read);

    imag_1_rows_V_c10_U : component fifo_w13_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Resize_U0_p_dst_rows_V_out_din,
        if_full_n => imag_1_rows_V_c10_full_n,
        if_write => Resize_U0_p_dst_rows_V_out_write,
        if_dout => imag_1_rows_V_c10_dout,
        if_empty_n => imag_1_rows_V_c10_empty_n,
        if_read => Mat2AXIvideo_U0_img_rows_V_read);

    imag_1_cols_V_c11_U : component fifo_w13_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Resize_U0_p_dst_cols_V_out_din,
        if_full_n => imag_1_cols_V_c11_full_n,
        if_write => Resize_U0_p_dst_cols_V_out_write,
        if_dout => imag_1_cols_V_c11_dout,
        if_empty_n => imag_1_cols_V_c11_empty_n,
        if_read => Mat2AXIvideo_U0_img_cols_V_read);

    start_for_Resize_U0_U : component start_for_Resize_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Resize_U0_din,
        if_full_n => start_for_Resize_U0_full_n,
        if_write => Block_proc_U0_start_write,
        if_dout => start_for_Resize_U0_dout,
        if_empty_n => start_for_Resize_U0_empty_n,
        if_read => Resize_U0_ap_ready);

    start_for_Mat2AXICeG_U : component start_for_Mat2AXICeG
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Mat2AXIvideo_U0_din,
        if_full_n => start_for_Mat2AXIvideo_U0_full_n,
        if_write => Resize_U0_start_write,
        if_dout => start_for_Mat2AXIvideo_U0_dout,
        if_empty_n => start_for_Mat2AXIvideo_U0_empty_n,
        if_read => Mat2AXIvideo_U0_ap_ready);




    AXIvideo2Mat_U0_ap_continue <= ap_const_logic_1;
    AXIvideo2Mat_U0_ap_start <= ap_const_logic_1;
    AXIvideo2Mat_U0_start_full_n <= ap_const_logic_1;
    AXIvideo2Mat_U0_start_write <= ap_const_logic_0;
    Block_proc_U0_ap_continue <= ap_const_logic_1;
    Block_proc_U0_ap_start <= ap_const_logic_1;
    Mat2AXIvideo_U0_ap_continue <= ap_const_logic_1;
    Mat2AXIvideo_U0_ap_start <= start_for_Mat2AXIvideo_U0_empty_n;
    Mat2AXIvideo_U0_start_full_n <= ap_const_logic_1;
    Mat2AXIvideo_U0_start_write <= ap_const_logic_0;
    Resize_U0_ap_continue <= ap_const_logic_1;
    Resize_U0_ap_start <= start_for_Resize_U0_empty_n;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_continue <= ap_const_logic_0;
    dst_axi_TDATA <= Mat2AXIvideo_U0_dst_axi_TDATA;
    dst_axi_TDEST <= Mat2AXIvideo_U0_dst_axi_TDEST;
    dst_axi_TID <= Mat2AXIvideo_U0_dst_axi_TID;
    dst_axi_TKEEP <= Mat2AXIvideo_U0_dst_axi_TKEEP;
    dst_axi_TLAST <= Mat2AXIvideo_U0_dst_axi_TLAST;
    dst_axi_TSTRB <= Mat2AXIvideo_U0_dst_axi_TSTRB;
    dst_axi_TUSER <= Mat2AXIvideo_U0_dst_axi_TUSER;
    dst_axi_TVALID <= Mat2AXIvideo_U0_dst_axi_TVALID;
    src_axi_TREADY <= AXIvideo2Mat_U0_src_axi_TREADY;
    start_for_Mat2AXIvideo_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_Resize_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
