-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sr_cast is
port (
    ap_ready : OUT STD_LOGIC;
    v_V : IN STD_LOGIC_VECTOR (29 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (7 downto 0) );
end;


architecture behav of sr_cast is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011101";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal tmp_fu_66_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_i_cast_fu_74_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_s_fu_48_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_Val2_1_fu_78_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_84_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_1_fu_58_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_92_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_104_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal carry_1_fu_98_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_ones_fu_114_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal Range1_all_zeros_fu_120_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal phitmp_demorgan_i_fu_134_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_40_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal phitmp_i_fu_140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal deleted_zeros_fu_126_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_110_demorgan_i_fu_152_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_not_fu_164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_not_i_fu_170_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal overflow_fu_158_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_not_i_fu_176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal neg_src_fu_146_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal brmerge_i_fu_182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_mux_i_fu_188_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_i_fu_196_p3 : STD_LOGIC_VECTOR (7 downto 0);


begin



    Range1_all_ones_fu_114_p2 <= "1" when (tmp_1_fu_104_p4 = ap_const_lv2_3) else "0";
    Range1_all_zeros_fu_120_p2 <= "1" when (tmp_1_fu_104_p4 = ap_const_lv2_0) else "0";
    ap_ready <= ap_const_logic_1;
    ap_return <= 
        p_mux_i_fu_188_p3 when (brmerge_i_fu_182_p2(0) = '1') else 
        p_i_fu_196_p3;
    brmerge_i_fu_182_p2 <= (p_not_i_fu_170_p2 or overflow_fu_158_p2);
    brmerge_not_i_fu_176_p2 <= (p_not_i_fu_170_p2 and p_110_demorgan_i_fu_152_p2);
    carry_1_fu_98_p2 <= (rev_fu_92_p2 and p_Result_1_fu_58_p3);
    deleted_zeros_fu_126_p3 <= 
        Range1_all_ones_fu_114_p2 when (carry_1_fu_98_p2(0) = '1') else 
        Range1_all_zeros_fu_120_p2;
    neg_src_fu_146_p2 <= (phitmp_i_fu_140_p2 and p_Result_s_fu_40_p3);
    overflow_fu_158_p2 <= (p_110_demorgan_i_fu_152_p2 xor ap_const_lv1_1);
    p_110_demorgan_i_fu_152_p2 <= (p_Result_s_fu_40_p3 or deleted_zeros_fu_126_p3);
    p_Result_1_fu_58_p3 <= v_V(27 downto 27);
    p_Result_not_fu_164_p2 <= (p_Result_s_fu_40_p3 xor ap_const_lv1_1);
    p_Result_s_fu_40_p3 <= v_V(29 downto 29);
    p_Val2_1_fu_78_p2 <= std_logic_vector(unsigned(tmp_5_i_cast_fu_74_p1) + unsigned(p_Val2_s_fu_48_p4));
    p_Val2_s_fu_48_p4 <= v_V(27 downto 20);
    p_i_fu_196_p3 <= 
        ap_const_lv8_0 when (neg_src_fu_146_p2(0) = '1') else 
        p_Val2_1_fu_78_p2;
    p_mux_i_fu_188_p3 <= 
        p_Val2_1_fu_78_p2 when (brmerge_not_i_fu_176_p2(0) = '1') else 
        ap_const_lv8_FF;
    p_not_i_fu_170_p2 <= (phitmp_demorgan_i_fu_134_p2 or p_Result_not_fu_164_p2);
    phitmp_demorgan_i_fu_134_p2 <= (carry_1_fu_98_p2 and Range1_all_ones_fu_114_p2);
    phitmp_i_fu_140_p2 <= (phitmp_demorgan_i_fu_134_p2 xor ap_const_lv1_1);
    rev_fu_92_p2 <= (tmp_2_fu_84_p3 xor ap_const_lv1_1);
    tmp_1_fu_104_p4 <= v_V(29 downto 28);
    tmp_2_fu_84_p3 <= p_Val2_1_fu_78_p2(7 downto 7);
    tmp_5_i_cast_fu_74_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_66_p3),8));
    tmp_fu_66_p3 <= v_V(19 downto 19);
end behav;
