// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="my_hls_resize,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg400-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=11.010000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=24,HLS_SYN_DSP=26,HLS_SYN_FF=9129,HLS_SYN_LUT=7140,HLS_VERSION=2018_3}" *)

module my_hls_resize (
        src_axi_TDATA,
        src_axi_TKEEP,
        src_axi_TSTRB,
        src_axi_TUSER,
        src_axi_TLAST,
        src_axi_TID,
        src_axi_TDEST,
        dst_axi_TDATA,
        dst_axi_TKEEP,
        dst_axi_TSTRB,
        dst_axi_TUSER,
        dst_axi_TLAST,
        dst_axi_TID,
        dst_axi_TDEST,
        ap_clk,
        ap_rst_n,
        src_axi_TVALID,
        src_axi_TREADY,
        dst_axi_TVALID,
        dst_axi_TREADY
);


input  [23:0] src_axi_TDATA;
input  [2:0] src_axi_TKEEP;
input  [2:0] src_axi_TSTRB;
input  [0:0] src_axi_TUSER;
input  [0:0] src_axi_TLAST;
input  [0:0] src_axi_TID;
input  [0:0] src_axi_TDEST;
output  [23:0] dst_axi_TDATA;
output  [2:0] dst_axi_TKEEP;
output  [2:0] dst_axi_TSTRB;
output  [0:0] dst_axi_TUSER;
output  [0:0] dst_axi_TLAST;
output  [0:0] dst_axi_TID;
output  [0:0] dst_axi_TDEST;
input   ap_clk;
input   ap_rst_n;
input   src_axi_TVALID;
output   src_axi_TREADY;
output   dst_axi_TVALID;
input   dst_axi_TREADY;

 reg    ap_rst_n_inv;
wire    Block_proc_U0_ap_start;
wire    Block_proc_U0_ap_done;
wire    Block_proc_U0_ap_continue;
wire    Block_proc_U0_ap_idle;
wire    Block_proc_U0_ap_ready;
wire    Block_proc_U0_start_out;
wire    Block_proc_U0_start_write;
wire   [10:0] Block_proc_U0_imag_0_rows_V_out_din;
wire    Block_proc_U0_imag_0_rows_V_out_write;
wire   [10:0] Block_proc_U0_imag_0_cols_V_out_din;
wire    Block_proc_U0_imag_0_cols_V_out_write;
wire   [12:0] Block_proc_U0_imag_1_rows_V_out_din;
wire    Block_proc_U0_imag_1_rows_V_out_write;
wire   [12:0] Block_proc_U0_imag_1_cols_V_out_din;
wire    Block_proc_U0_imag_1_cols_V_out_write;
wire    AXIvideo2Mat_U0_ap_start;
wire    AXIvideo2Mat_U0_ap_done;
wire    AXIvideo2Mat_U0_ap_continue;
wire    AXIvideo2Mat_U0_ap_idle;
wire    AXIvideo2Mat_U0_ap_ready;
wire    AXIvideo2Mat_U0_src_axi_TREADY;
wire    AXIvideo2Mat_U0_img_rows_V_read;
wire    AXIvideo2Mat_U0_img_cols_V_read;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_0_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_0_V_write;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_1_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_1_V_write;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_2_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_2_V_write;
wire   [10:0] AXIvideo2Mat_U0_img_rows_V_out_din;
wire    AXIvideo2Mat_U0_img_rows_V_out_write;
wire   [10:0] AXIvideo2Mat_U0_img_cols_V_out_din;
wire    AXIvideo2Mat_U0_img_cols_V_out_write;
wire    Resize_U0_ap_start;
wire    Resize_U0_ap_done;
wire    Resize_U0_ap_continue;
wire    Resize_U0_ap_idle;
wire    Resize_U0_ap_ready;
wire    Resize_U0_start_out;
wire    Resize_U0_start_write;
wire    Resize_U0_p_src_rows_V_read;
wire    Resize_U0_p_src_cols_V_read;
wire    Resize_U0_p_src_data_stream_0_V_read;
wire    Resize_U0_p_src_data_stream_1_V_read;
wire    Resize_U0_p_src_data_stream_2_V_read;
wire    Resize_U0_p_dst_rows_V_read;
wire    Resize_U0_p_dst_cols_V_read;
wire   [7:0] Resize_U0_p_dst_data_stream_0_V_din;
wire    Resize_U0_p_dst_data_stream_0_V_write;
wire   [7:0] Resize_U0_p_dst_data_stream_1_V_din;
wire    Resize_U0_p_dst_data_stream_1_V_write;
wire   [7:0] Resize_U0_p_dst_data_stream_2_V_din;
wire    Resize_U0_p_dst_data_stream_2_V_write;
wire   [12:0] Resize_U0_p_dst_rows_V_out_din;
wire    Resize_U0_p_dst_rows_V_out_write;
wire   [12:0] Resize_U0_p_dst_cols_V_out_din;
wire    Resize_U0_p_dst_cols_V_out_write;
wire    Mat2AXIvideo_U0_ap_start;
wire    Mat2AXIvideo_U0_ap_done;
wire    Mat2AXIvideo_U0_ap_continue;
wire    Mat2AXIvideo_U0_ap_idle;
wire    Mat2AXIvideo_U0_ap_ready;
wire    Mat2AXIvideo_U0_img_rows_V_read;
wire    Mat2AXIvideo_U0_img_cols_V_read;
wire    Mat2AXIvideo_U0_img_data_stream_0_V_read;
wire    Mat2AXIvideo_U0_img_data_stream_1_V_read;
wire    Mat2AXIvideo_U0_img_data_stream_2_V_read;
wire   [23:0] Mat2AXIvideo_U0_dst_axi_TDATA;
wire    Mat2AXIvideo_U0_dst_axi_TVALID;
wire   [2:0] Mat2AXIvideo_U0_dst_axi_TKEEP;
wire   [2:0] Mat2AXIvideo_U0_dst_axi_TSTRB;
wire   [0:0] Mat2AXIvideo_U0_dst_axi_TUSER;
wire   [0:0] Mat2AXIvideo_U0_dst_axi_TLAST;
wire   [0:0] Mat2AXIvideo_U0_dst_axi_TID;
wire   [0:0] Mat2AXIvideo_U0_dst_axi_TDEST;
wire    ap_sync_continue;
wire    imag_0_rows_V_c_full_n;
wire   [10:0] imag_0_rows_V_c_dout;
wire    imag_0_rows_V_c_empty_n;
wire    imag_0_cols_V_c_full_n;
wire   [10:0] imag_0_cols_V_c_dout;
wire    imag_0_cols_V_c_empty_n;
wire    imag_1_rows_V_c_full_n;
wire   [12:0] imag_1_rows_V_c_dout;
wire    imag_1_rows_V_c_empty_n;
wire    imag_1_cols_V_c_full_n;
wire   [12:0] imag_1_cols_V_c_dout;
wire    imag_1_cols_V_c_empty_n;
wire    imag_0_data_stream_0_full_n;
wire   [7:0] imag_0_data_stream_0_dout;
wire    imag_0_data_stream_0_empty_n;
wire    imag_0_data_stream_1_full_n;
wire   [7:0] imag_0_data_stream_1_dout;
wire    imag_0_data_stream_1_empty_n;
wire    imag_0_data_stream_2_full_n;
wire   [7:0] imag_0_data_stream_2_dout;
wire    imag_0_data_stream_2_empty_n;
wire    imag_0_rows_V_c8_full_n;
wire   [10:0] imag_0_rows_V_c8_dout;
wire    imag_0_rows_V_c8_empty_n;
wire    imag_0_cols_V_c9_full_n;
wire   [10:0] imag_0_cols_V_c9_dout;
wire    imag_0_cols_V_c9_empty_n;
wire    imag_1_data_stream_0_full_n;
wire   [7:0] imag_1_data_stream_0_dout;
wire    imag_1_data_stream_0_empty_n;
wire    imag_1_data_stream_1_full_n;
wire   [7:0] imag_1_data_stream_1_dout;
wire    imag_1_data_stream_1_empty_n;
wire    imag_1_data_stream_2_full_n;
wire   [7:0] imag_1_data_stream_2_dout;
wire    imag_1_data_stream_2_empty_n;
wire    imag_1_rows_V_c10_full_n;
wire   [12:0] imag_1_rows_V_c10_dout;
wire    imag_1_rows_V_c10_empty_n;
wire    imag_1_cols_V_c11_full_n;
wire   [12:0] imag_1_cols_V_c11_dout;
wire    imag_1_cols_V_c11_empty_n;
wire   [0:0] start_for_Resize_U0_din;
wire    start_for_Resize_U0_full_n;
wire   [0:0] start_for_Resize_U0_dout;
wire    start_for_Resize_U0_empty_n;
wire    AXIvideo2Mat_U0_start_full_n;
wire    AXIvideo2Mat_U0_start_write;
wire   [0:0] start_for_Mat2AXIvideo_U0_din;
wire    start_for_Mat2AXIvideo_U0_full_n;
wire   [0:0] start_for_Mat2AXIvideo_U0_dout;
wire    start_for_Mat2AXIvideo_U0_empty_n;
wire    Mat2AXIvideo_U0_start_full_n;
wire    Mat2AXIvideo_U0_start_write;

Block_proc Block_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_proc_U0_ap_start),
    .start_full_n(start_for_Resize_U0_full_n),
    .ap_done(Block_proc_U0_ap_done),
    .ap_continue(Block_proc_U0_ap_continue),
    .ap_idle(Block_proc_U0_ap_idle),
    .ap_ready(Block_proc_U0_ap_ready),
    .start_out(Block_proc_U0_start_out),
    .start_write(Block_proc_U0_start_write),
    .imag_0_rows_V_out_din(Block_proc_U0_imag_0_rows_V_out_din),
    .imag_0_rows_V_out_full_n(imag_0_rows_V_c_full_n),
    .imag_0_rows_V_out_write(Block_proc_U0_imag_0_rows_V_out_write),
    .imag_0_cols_V_out_din(Block_proc_U0_imag_0_cols_V_out_din),
    .imag_0_cols_V_out_full_n(imag_0_cols_V_c_full_n),
    .imag_0_cols_V_out_write(Block_proc_U0_imag_0_cols_V_out_write),
    .imag_1_rows_V_out_din(Block_proc_U0_imag_1_rows_V_out_din),
    .imag_1_rows_V_out_full_n(imag_1_rows_V_c_full_n),
    .imag_1_rows_V_out_write(Block_proc_U0_imag_1_rows_V_out_write),
    .imag_1_cols_V_out_din(Block_proc_U0_imag_1_cols_V_out_din),
    .imag_1_cols_V_out_full_n(imag_1_cols_V_c_full_n),
    .imag_1_cols_V_out_write(Block_proc_U0_imag_1_cols_V_out_write)
);

AXIvideo2Mat AXIvideo2Mat_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIvideo2Mat_U0_ap_start),
    .ap_done(AXIvideo2Mat_U0_ap_done),
    .ap_continue(AXIvideo2Mat_U0_ap_continue),
    .ap_idle(AXIvideo2Mat_U0_ap_idle),
    .ap_ready(AXIvideo2Mat_U0_ap_ready),
    .src_axi_TDATA(src_axi_TDATA),
    .src_axi_TVALID(src_axi_TVALID),
    .src_axi_TREADY(AXIvideo2Mat_U0_src_axi_TREADY),
    .src_axi_TKEEP(src_axi_TKEEP),
    .src_axi_TSTRB(src_axi_TSTRB),
    .src_axi_TUSER(src_axi_TUSER),
    .src_axi_TLAST(src_axi_TLAST),
    .src_axi_TID(src_axi_TID),
    .src_axi_TDEST(src_axi_TDEST),
    .img_rows_V_dout(imag_0_rows_V_c_dout),
    .img_rows_V_empty_n(imag_0_rows_V_c_empty_n),
    .img_rows_V_read(AXIvideo2Mat_U0_img_rows_V_read),
    .img_cols_V_dout(imag_0_cols_V_c_dout),
    .img_cols_V_empty_n(imag_0_cols_V_c_empty_n),
    .img_cols_V_read(AXIvideo2Mat_U0_img_cols_V_read),
    .img_data_stream_0_V_din(AXIvideo2Mat_U0_img_data_stream_0_V_din),
    .img_data_stream_0_V_full_n(imag_0_data_stream_0_full_n),
    .img_data_stream_0_V_write(AXIvideo2Mat_U0_img_data_stream_0_V_write),
    .img_data_stream_1_V_din(AXIvideo2Mat_U0_img_data_stream_1_V_din),
    .img_data_stream_1_V_full_n(imag_0_data_stream_1_full_n),
    .img_data_stream_1_V_write(AXIvideo2Mat_U0_img_data_stream_1_V_write),
    .img_data_stream_2_V_din(AXIvideo2Mat_U0_img_data_stream_2_V_din),
    .img_data_stream_2_V_full_n(imag_0_data_stream_2_full_n),
    .img_data_stream_2_V_write(AXIvideo2Mat_U0_img_data_stream_2_V_write),
    .img_rows_V_out_din(AXIvideo2Mat_U0_img_rows_V_out_din),
    .img_rows_V_out_full_n(imag_0_rows_V_c8_full_n),
    .img_rows_V_out_write(AXIvideo2Mat_U0_img_rows_V_out_write),
    .img_cols_V_out_din(AXIvideo2Mat_U0_img_cols_V_out_din),
    .img_cols_V_out_full_n(imag_0_cols_V_c9_full_n),
    .img_cols_V_out_write(AXIvideo2Mat_U0_img_cols_V_out_write)
);

Resize Resize_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Resize_U0_ap_start),
    .start_full_n(start_for_Mat2AXIvideo_U0_full_n),
    .ap_done(Resize_U0_ap_done),
    .ap_continue(Resize_U0_ap_continue),
    .ap_idle(Resize_U0_ap_idle),
    .ap_ready(Resize_U0_ap_ready),
    .start_out(Resize_U0_start_out),
    .start_write(Resize_U0_start_write),
    .p_src_rows_V_dout(imag_0_rows_V_c8_dout),
    .p_src_rows_V_empty_n(imag_0_rows_V_c8_empty_n),
    .p_src_rows_V_read(Resize_U0_p_src_rows_V_read),
    .p_src_cols_V_dout(imag_0_cols_V_c9_dout),
    .p_src_cols_V_empty_n(imag_0_cols_V_c9_empty_n),
    .p_src_cols_V_read(Resize_U0_p_src_cols_V_read),
    .p_src_data_stream_0_V_dout(imag_0_data_stream_0_dout),
    .p_src_data_stream_0_V_empty_n(imag_0_data_stream_0_empty_n),
    .p_src_data_stream_0_V_read(Resize_U0_p_src_data_stream_0_V_read),
    .p_src_data_stream_1_V_dout(imag_0_data_stream_1_dout),
    .p_src_data_stream_1_V_empty_n(imag_0_data_stream_1_empty_n),
    .p_src_data_stream_1_V_read(Resize_U0_p_src_data_stream_1_V_read),
    .p_src_data_stream_2_V_dout(imag_0_data_stream_2_dout),
    .p_src_data_stream_2_V_empty_n(imag_0_data_stream_2_empty_n),
    .p_src_data_stream_2_V_read(Resize_U0_p_src_data_stream_2_V_read),
    .p_dst_rows_V_dout(imag_1_rows_V_c_dout),
    .p_dst_rows_V_empty_n(imag_1_rows_V_c_empty_n),
    .p_dst_rows_V_read(Resize_U0_p_dst_rows_V_read),
    .p_dst_cols_V_dout(imag_1_cols_V_c_dout),
    .p_dst_cols_V_empty_n(imag_1_cols_V_c_empty_n),
    .p_dst_cols_V_read(Resize_U0_p_dst_cols_V_read),
    .p_dst_data_stream_0_V_din(Resize_U0_p_dst_data_stream_0_V_din),
    .p_dst_data_stream_0_V_full_n(imag_1_data_stream_0_full_n),
    .p_dst_data_stream_0_V_write(Resize_U0_p_dst_data_stream_0_V_write),
    .p_dst_data_stream_1_V_din(Resize_U0_p_dst_data_stream_1_V_din),
    .p_dst_data_stream_1_V_full_n(imag_1_data_stream_1_full_n),
    .p_dst_data_stream_1_V_write(Resize_U0_p_dst_data_stream_1_V_write),
    .p_dst_data_stream_2_V_din(Resize_U0_p_dst_data_stream_2_V_din),
    .p_dst_data_stream_2_V_full_n(imag_1_data_stream_2_full_n),
    .p_dst_data_stream_2_V_write(Resize_U0_p_dst_data_stream_2_V_write),
    .p_dst_rows_V_out_din(Resize_U0_p_dst_rows_V_out_din),
    .p_dst_rows_V_out_full_n(imag_1_rows_V_c10_full_n),
    .p_dst_rows_V_out_write(Resize_U0_p_dst_rows_V_out_write),
    .p_dst_cols_V_out_din(Resize_U0_p_dst_cols_V_out_din),
    .p_dst_cols_V_out_full_n(imag_1_cols_V_c11_full_n),
    .p_dst_cols_V_out_write(Resize_U0_p_dst_cols_V_out_write)
);

Mat2AXIvideo Mat2AXIvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Mat2AXIvideo_U0_ap_start),
    .ap_done(Mat2AXIvideo_U0_ap_done),
    .ap_continue(Mat2AXIvideo_U0_ap_continue),
    .ap_idle(Mat2AXIvideo_U0_ap_idle),
    .ap_ready(Mat2AXIvideo_U0_ap_ready),
    .img_rows_V_dout(imag_1_rows_V_c10_dout),
    .img_rows_V_empty_n(imag_1_rows_V_c10_empty_n),
    .img_rows_V_read(Mat2AXIvideo_U0_img_rows_V_read),
    .img_cols_V_dout(imag_1_cols_V_c11_dout),
    .img_cols_V_empty_n(imag_1_cols_V_c11_empty_n),
    .img_cols_V_read(Mat2AXIvideo_U0_img_cols_V_read),
    .img_data_stream_0_V_dout(imag_1_data_stream_0_dout),
    .img_data_stream_0_V_empty_n(imag_1_data_stream_0_empty_n),
    .img_data_stream_0_V_read(Mat2AXIvideo_U0_img_data_stream_0_V_read),
    .img_data_stream_1_V_dout(imag_1_data_stream_1_dout),
    .img_data_stream_1_V_empty_n(imag_1_data_stream_1_empty_n),
    .img_data_stream_1_V_read(Mat2AXIvideo_U0_img_data_stream_1_V_read),
    .img_data_stream_2_V_dout(imag_1_data_stream_2_dout),
    .img_data_stream_2_V_empty_n(imag_1_data_stream_2_empty_n),
    .img_data_stream_2_V_read(Mat2AXIvideo_U0_img_data_stream_2_V_read),
    .dst_axi_TDATA(Mat2AXIvideo_U0_dst_axi_TDATA),
    .dst_axi_TVALID(Mat2AXIvideo_U0_dst_axi_TVALID),
    .dst_axi_TREADY(dst_axi_TREADY),
    .dst_axi_TKEEP(Mat2AXIvideo_U0_dst_axi_TKEEP),
    .dst_axi_TSTRB(Mat2AXIvideo_U0_dst_axi_TSTRB),
    .dst_axi_TUSER(Mat2AXIvideo_U0_dst_axi_TUSER),
    .dst_axi_TLAST(Mat2AXIvideo_U0_dst_axi_TLAST),
    .dst_axi_TID(Mat2AXIvideo_U0_dst_axi_TID),
    .dst_axi_TDEST(Mat2AXIvideo_U0_dst_axi_TDEST)
);

fifo_w11_d2_A imag_0_rows_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_imag_0_rows_V_out_din),
    .if_full_n(imag_0_rows_V_c_full_n),
    .if_write(Block_proc_U0_imag_0_rows_V_out_write),
    .if_dout(imag_0_rows_V_c_dout),
    .if_empty_n(imag_0_rows_V_c_empty_n),
    .if_read(AXIvideo2Mat_U0_img_rows_V_read)
);

fifo_w11_d2_A imag_0_cols_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_imag_0_cols_V_out_din),
    .if_full_n(imag_0_cols_V_c_full_n),
    .if_write(Block_proc_U0_imag_0_cols_V_out_write),
    .if_dout(imag_0_cols_V_c_dout),
    .if_empty_n(imag_0_cols_V_c_empty_n),
    .if_read(AXIvideo2Mat_U0_img_cols_V_read)
);

fifo_w13_d3_A imag_1_rows_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_imag_1_rows_V_out_din),
    .if_full_n(imag_1_rows_V_c_full_n),
    .if_write(Block_proc_U0_imag_1_rows_V_out_write),
    .if_dout(imag_1_rows_V_c_dout),
    .if_empty_n(imag_1_rows_V_c_empty_n),
    .if_read(Resize_U0_p_dst_rows_V_read)
);

fifo_w13_d3_A imag_1_cols_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_imag_1_cols_V_out_din),
    .if_full_n(imag_1_cols_V_c_full_n),
    .if_write(Block_proc_U0_imag_1_cols_V_out_write),
    .if_dout(imag_1_cols_V_c_dout),
    .if_empty_n(imag_1_cols_V_c_empty_n),
    .if_read(Resize_U0_p_dst_cols_V_read)
);

fifo_w8_d2_A imag_0_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_0_V_din),
    .if_full_n(imag_0_data_stream_0_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_0_V_write),
    .if_dout(imag_0_data_stream_0_dout),
    .if_empty_n(imag_0_data_stream_0_empty_n),
    .if_read(Resize_U0_p_src_data_stream_0_V_read)
);

fifo_w8_d2_A imag_0_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_1_V_din),
    .if_full_n(imag_0_data_stream_1_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_1_V_write),
    .if_dout(imag_0_data_stream_1_dout),
    .if_empty_n(imag_0_data_stream_1_empty_n),
    .if_read(Resize_U0_p_src_data_stream_1_V_read)
);

fifo_w8_d2_A imag_0_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_2_V_din),
    .if_full_n(imag_0_data_stream_2_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_2_V_write),
    .if_dout(imag_0_data_stream_2_dout),
    .if_empty_n(imag_0_data_stream_2_empty_n),
    .if_read(Resize_U0_p_src_data_stream_2_V_read)
);

fifo_w11_d2_A imag_0_rows_V_c8_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_rows_V_out_din),
    .if_full_n(imag_0_rows_V_c8_full_n),
    .if_write(AXIvideo2Mat_U0_img_rows_V_out_write),
    .if_dout(imag_0_rows_V_c8_dout),
    .if_empty_n(imag_0_rows_V_c8_empty_n),
    .if_read(Resize_U0_p_src_rows_V_read)
);

fifo_w11_d2_A imag_0_cols_V_c9_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_cols_V_out_din),
    .if_full_n(imag_0_cols_V_c9_full_n),
    .if_write(AXIvideo2Mat_U0_img_cols_V_out_write),
    .if_dout(imag_0_cols_V_c9_dout),
    .if_empty_n(imag_0_cols_V_c9_empty_n),
    .if_read(Resize_U0_p_src_cols_V_read)
);

fifo_w8_d2_A imag_1_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Resize_U0_p_dst_data_stream_0_V_din),
    .if_full_n(imag_1_data_stream_0_full_n),
    .if_write(Resize_U0_p_dst_data_stream_0_V_write),
    .if_dout(imag_1_data_stream_0_dout),
    .if_empty_n(imag_1_data_stream_0_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_0_V_read)
);

fifo_w8_d2_A imag_1_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Resize_U0_p_dst_data_stream_1_V_din),
    .if_full_n(imag_1_data_stream_1_full_n),
    .if_write(Resize_U0_p_dst_data_stream_1_V_write),
    .if_dout(imag_1_data_stream_1_dout),
    .if_empty_n(imag_1_data_stream_1_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_1_V_read)
);

fifo_w8_d2_A imag_1_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Resize_U0_p_dst_data_stream_2_V_din),
    .if_full_n(imag_1_data_stream_2_full_n),
    .if_write(Resize_U0_p_dst_data_stream_2_V_write),
    .if_dout(imag_1_data_stream_2_dout),
    .if_empty_n(imag_1_data_stream_2_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_2_V_read)
);

fifo_w13_d2_A imag_1_rows_V_c10_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Resize_U0_p_dst_rows_V_out_din),
    .if_full_n(imag_1_rows_V_c10_full_n),
    .if_write(Resize_U0_p_dst_rows_V_out_write),
    .if_dout(imag_1_rows_V_c10_dout),
    .if_empty_n(imag_1_rows_V_c10_empty_n),
    .if_read(Mat2AXIvideo_U0_img_rows_V_read)
);

fifo_w13_d2_A imag_1_cols_V_c11_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Resize_U0_p_dst_cols_V_out_din),
    .if_full_n(imag_1_cols_V_c11_full_n),
    .if_write(Resize_U0_p_dst_cols_V_out_write),
    .if_dout(imag_1_cols_V_c11_dout),
    .if_empty_n(imag_1_cols_V_c11_empty_n),
    .if_read(Mat2AXIvideo_U0_img_cols_V_read)
);

start_for_Resize_U0 start_for_Resize_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Resize_U0_din),
    .if_full_n(start_for_Resize_U0_full_n),
    .if_write(Block_proc_U0_start_write),
    .if_dout(start_for_Resize_U0_dout),
    .if_empty_n(start_for_Resize_U0_empty_n),
    .if_read(Resize_U0_ap_ready)
);

start_for_Mat2AXICeG start_for_Mat2AXICeG_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Mat2AXIvideo_U0_din),
    .if_full_n(start_for_Mat2AXIvideo_U0_full_n),
    .if_write(Resize_U0_start_write),
    .if_dout(start_for_Mat2AXIvideo_U0_dout),
    .if_empty_n(start_for_Mat2AXIvideo_U0_empty_n),
    .if_read(Mat2AXIvideo_U0_ap_ready)
);

assign AXIvideo2Mat_U0_ap_continue = 1'b1;

assign AXIvideo2Mat_U0_ap_start = 1'b1;

assign AXIvideo2Mat_U0_start_full_n = 1'b1;

assign AXIvideo2Mat_U0_start_write = 1'b0;

assign Block_proc_U0_ap_continue = 1'b1;

assign Block_proc_U0_ap_start = 1'b1;

assign Mat2AXIvideo_U0_ap_continue = 1'b1;

assign Mat2AXIvideo_U0_ap_start = start_for_Mat2AXIvideo_U0_empty_n;

assign Mat2AXIvideo_U0_start_full_n = 1'b1;

assign Mat2AXIvideo_U0_start_write = 1'b0;

assign Resize_U0_ap_continue = 1'b1;

assign Resize_U0_ap_start = start_for_Resize_U0_empty_n;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b0;

assign dst_axi_TDATA = Mat2AXIvideo_U0_dst_axi_TDATA;

assign dst_axi_TDEST = Mat2AXIvideo_U0_dst_axi_TDEST;

assign dst_axi_TID = Mat2AXIvideo_U0_dst_axi_TID;

assign dst_axi_TKEEP = Mat2AXIvideo_U0_dst_axi_TKEEP;

assign dst_axi_TLAST = Mat2AXIvideo_U0_dst_axi_TLAST;

assign dst_axi_TSTRB = Mat2AXIvideo_U0_dst_axi_TSTRB;

assign dst_axi_TUSER = Mat2AXIvideo_U0_dst_axi_TUSER;

assign dst_axi_TVALID = Mat2AXIvideo_U0_dst_axi_TVALID;

assign src_axi_TREADY = AXIvideo2Mat_U0_src_axi_TREADY;

assign start_for_Mat2AXIvideo_U0_din = 1'b1;

assign start_for_Resize_U0_din = 1'b1;

endmodule //my_hls_resize
